# -*- coding: utf-8 -*-
"""NetworkProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146M7EOyL3ssRxP9YJDt1PzgXd16zW2GK
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import erfc
import json
from tabulate import tabulate

# ============================================================
#  SETTINGS & PARAMETERS
# ============================================================
NUM_BITS = 200_000
SNR_DB = np.arange(0, 21)

# Theoretical formulas - higher resolution
SNR_DB_THEORY = np.linspace(0, 20, 100)

# ============================================================
#  AWGN FUNCTION
# ============================================================
def add_awgn(signal, snr_db, bits_per_symbol):
    snr_linear = 10 ** (snr_db / 10)
    noise_power = 1 / (2 * bits_per_symbol * snr_linear)
    noise = np.sqrt(noise_power) * np.random.randn(*signal.shape)
    return signal + noise

# ============================================================
#  BPSK
# ============================================================
def simulate_bpsk(snr_db):
    bits = np.random.randint(0, 2, NUM_BITS)
    signal = 2 * bits - 1

    ber_list = []

    for snr in snr_db:
        received = add_awgn(signal.astype(float), snr, 1)
        decided = (received > 0).astype(int)

        ber = np.mean(decided != bits)
        ber_list.append(max(ber, 1e-6))

    return np.array(ber_list)

def theoretical_bpsk_ber(snr_db):
    snr_linear = 10 ** (np.array(snr_db) / 10)
    return 0.5 * erfc(np.sqrt(snr_linear))

# ============================================================
#  QPSK
# ============================================================
def simulate_qpsk(snr_db):

    bits = np.random.randint(0, 2, NUM_BITS)

    if len(bits) % 2 != 0:
        bits = bits[:-1]

    I_bits = bits[0::2]
    Q_bits = bits[1::2]

    I_signal = (2 * I_bits - 1) / np.sqrt(2)
    Q_signal = (2 * Q_bits - 1) / np.sqrt(2)

    ber_list = []

    for snr in snr_db:

        I_rx = add_awgn(I_signal, snr, 2)
        Q_rx = add_awgn(Q_signal, snr, 2)

        I_dec = (I_rx > 0).astype(int)
        Q_dec = (Q_rx > 0).astype(int)

        errors = np.sum(I_dec != I_bits) + np.sum(Q_dec != Q_bits)

        ber = errors / len(bits)

        ber_list.append(max(ber, 1e-6))

    return np.array(ber_list)

def theoretical_qpsk_ber(snr_db):

    snr_linear = 10 ** (np.array(snr_db) / 10)

    return 0.5 * erfc(np.sqrt(snr_linear))

# ============================================================
#  QAM
# ============================================================
def simulate_qam(snr_db, M):

    bits_per_sym = int(np.log2(M))

    half = int(np.sqrt(M))

    levels = np.arange(-(half - 1), half, 2)

    bits_per_dim = bits_per_sym // 2

    total_syms = NUM_BITS // bits_per_sym

    total_bits = total_syms * bits_per_sym

    bits = np.random.randint(0, 2, total_bits)

    bits_matrix = bits.reshape(total_syms, bits_per_sym)

    def bits_to_level(b_block):

        idx = b_block.dot(
            1 << np.arange(b_block.shape[1] - 1, -1, -1)
        )

        return levels[idx]

    I_sym_raw = bits_to_level(
        bits_matrix[:, :bits_per_dim]
    ).astype(float)

    Q_sym_raw = bits_to_level(
        bits_matrix[:, bits_per_dim:]
    ).astype(float)

    avg_power = np.mean(I_sym_raw**2 + Q_sym_raw**2)

    def decide(rx):

        return np.argmin(
            np.abs(rx[:, None] - levels[None, :]),
            axis=1
        )

    I_idx_tx = decide(I_sym_raw)
    Q_idx_tx = decide(Q_sym_raw)

    def gray_errors(tx, rx):

        tx_g = tx ^ (tx >> 1)
        rx_g = rx ^ (rx >> 1)

        return sum(
            bin(a ^ b).count('1')
            for a, b in zip(tx_g, rx_g)
        )

    ber_list = []

    for snr in snr_db:

        snr_linear = 10 ** (snr / 10)

        noise_std = np.sqrt(
            avg_power / (2 * bits_per_sym * snr_linear)
        )

        I_rx = I_sym_raw + noise_std * np.random.randn(total_syms)

        Q_rx = Q_sym_raw + noise_std * np.random.randn(total_syms)

        I_idx_rx = decide(I_rx)
        Q_idx_rx = decide(Q_rx)

        errors = (
            gray_errors(I_idx_tx, I_idx_rx)
            +
            gray_errors(Q_idx_tx, Q_idx_rx)
        )

        ber = errors / total_bits

        ber_list.append(max(ber, 1e-6))

    return np.array(ber_list)

def theoretical_qam_ber(snr_db, M):

    snr_linear = 10 ** (np.array(snr_db) / 10)

    k = np.log2(M)

    return (
        (4 / k)
        *
        (1 - 1 / np.sqrt(M))
        *
        0.5
        *
        erfc(
            np.sqrt(
                1.5 * k * snr_linear / (M - 1)
            )
        )
    )

# ============================================================
#  CONSTELLATION DIAGRAMS
# ============================================================
def plot_constellation_diagrams():

    fig, axes = plt.subplots(3, 2, figsize=(14, 16))

    fig.suptitle(
        'Constellation Diagrams of Digital Modulation Schemes',
        fontsize=16,
        fontweight='bold'
    )

    # --------------------------------------------------------
    # BPSK
    # --------------------------------------------------------
    bpsk_points = np.array([-1, 1])

    axes[0, 0].scatter(
        bpsk_points,
        [0, 0],
        c='blue',
        s=150,
        marker='o',
        edgecolors='black'
    )

    axes[0, 0].set_title(
        'BPSK Constellation (1 bit/symbol)',
        fontweight='bold'
    )

    axes[0, 0].set_xlabel('In-Phase (I)')
    axes[0, 0].set_ylabel('Quadrature (Q)')
    axes[0, 0].grid(True, alpha=0.3)

    axes[0, 0].set_xlim(-2, 2)
    axes[0, 0].set_ylim(-2, 2)

    # --------------------------------------------------------
    # QPSK
    # --------------------------------------------------------
    qpsk_points = np.array([
        1+1j,
        1-1j,
        -1+1j,
        -1-1j
    ]) / np.sqrt(2)

    axes[0, 1].scatter(
        np.real(qpsk_points),
        np.imag(qpsk_points),
        c='green',
        s=150,
        marker='o',
        edgecolors='black'
    )

    axes[0, 1].set_title(
        'QPSK Constellation (2 bits/symbol)',
        fontweight='bold'
    )

    axes[0, 1].set_xlabel('In-Phase (I)')
    axes[0, 1].set_ylabel('Quadrature (Q)')
    axes[0, 1].grid(True, alpha=0.3)

    axes[0, 1].set_xlim(-1.5, 1.5)
    axes[0, 1].set_ylim(-1.5, 1.5)

    # --------------------------------------------------------
    # 16-QAM
    # --------------------------------------------------------
    lv16 = np.array([-3, -1, 1, 3])

    pts16 = np.array([
        i + 1j*q
        for i in lv16
        for q in lv16
    ])

    pts16 /= np.sqrt(np.mean(np.abs(pts16)**2))

    axes[1, 0].scatter(
        np.real(pts16),
        np.imag(pts16),
        c='orange',
        s=100
    )

    axes[1, 0].set_title(
        '16-QAM Constellation (4 bits/symbol)',
        fontweight='bold'
    )

    axes[1, 0].set_xlabel('In-Phase (I)')
    axes[1, 0].set_ylabel('Quadrature (Q)')
    axes[1, 0].grid(True, alpha=0.3)

    axes[1, 0].set_xlim(-1.5, 1.5)
    axes[1, 0].set_ylim(-1.5, 1.5)

    # --------------------------------------------------------
    # 64-QAM
    # --------------------------------------------------------
    lv64 = np.arange(-7, 8, 2)

    pts64 = np.array([
        i + 1j*q
        for i in lv64
        for q in lv64
    ])

    pts64 /= np.sqrt(np.mean(np.abs(pts64)**2))

    axes[1, 1].scatter(
        np.real(pts64),
        np.imag(pts64),
        c='red',
        s=40,
        alpha=0.7
    )

    axes[1, 1].set_title(
        '64-QAM Constellation (6 bits/symbol)',
        fontweight='bold'
    )

    axes[1, 1].set_xlabel('In-Phase (I)')
    axes[1, 1].set_ylabel('Quadrature (Q)')
    axes[1, 1].grid(True, alpha=0.3)

    axes[1, 1].set_xlim(-1.5, 1.5)
    axes[1, 1].set_ylim(-1.5, 1.5)

    # --------------------------------------------------------
    # 256-QAM
    # --------------------------------------------------------
    lv256 = np.arange(-15, 16, 2)

    pts256 = np.array([
        i + 1j*q
        for i in lv256
        for q in lv256
    ])

    pts256 /= np.sqrt(np.mean(np.abs(pts256)**2))

    axes[2, 0].scatter(
        np.real(pts256),
        np.imag(pts256),
        c='purple',
        s=12,
        alpha=0.7
    )

    axes[2, 0].set_title(
        '256-QAM Constellation (8 bits/symbol)',
        fontweight='bold'
    )

    axes[2, 0].set_xlabel('In-Phase (I)')
    axes[2, 0].set_ylabel('Quadrature (Q)')
    axes[2, 0].grid(True, alpha=0.3)

    axes[2, 0].set_xlim(-1.5, 1.5)
    axes[2, 0].set_ylim(-1.5, 1.5)

    # Empty subplot
    axes[2, 1].axis('off')

    plt.tight_layout()

    plt.savefig(
        'constellation_diagrams.png',
        dpi=150,
        bbox_inches='tight'
    )

    plt.show()

    print("✓ Saved: constellation_diagrams.png")

# ============================================================
#  SPECTRAL EFFICIENCY
# ============================================================
def plot_spectral_efficiency(ber_curves):

    modulations = [
        'BPSK',
        'QPSK',
        '16-QAM',
        '64-QAM',
        '256-QAM'
    ]

    bits_per_symbol = [1, 2, 4, 6, 8]

    def find_snr_for_ber(
        snr_points,
        ber_points,
        target=1e-3
    ):

        idx = np.where(ber_points <= target)[0]

        return (
            snr_points[idx[0]]
            if len(idx) > 0
            else 20.0
        )

    snr_required = [
        find_snr_for_ber(SNR_DB, curve)
        for curve in ber_curves
    ]

    plt.figure(figsize=(11, 7))

    colors = [
        'blue',
        'green',
        'orange',
        'red',
        'purple'
    ]

    bars = plt.bar(
        modulations,
        bits_per_symbol,
        color=colors,
        alpha=0.7,
        edgecolor='black'
    )

    for bar, bps, snr in zip(
        bars,
        bits_per_symbol,
        snr_required
    ):

        plt.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.2,
            f'{bps} bits/s/Hz',
            ha='center',
            fontsize=9,
            fontweight='bold'
        )

    plt.xlabel(
        'Modulation Scheme',
        fontsize=13,
        fontweight='bold'
    )

    plt.ylabel(
        'Spectral Efficiency (bits/s/Hz)',
        fontsize=13,
        fontweight='bold'
    )

    plt.title(
        'Spectral Efficiency Comparison',
        fontsize=14,
        fontweight='bold'
    )

    plt.grid(True, alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        'spectral_efficiency_comparison.png',
        dpi=150,
        bbox_inches='tight'
    )

    plt.show()

    print("✓ Saved: spectral_efficiency_comparison.png")

# ============================================================
#  PERFORMANCE METRICS
# ============================================================
def calculate_performance_metrics(
    ber_curves,
    modulations,
    bits_per_symbol
):

    def find_snr_for_ber(
        snr_points,
        ber_points,
        target=1e-3
    ):

        idx = np.where(ber_points <= target)[0]

        if len(idx) > 0:
            return snr_points[idx[0]]

        return 20.0

    metrics = {}

    for mod, ber_curve, bps in zip(
        modulations,
        ber_curves,
        bits_per_symbol
    ):

        snr_sensitivity = find_snr_for_ber(
            SNR_DB,
            ber_curve
        )

        idx_10db = np.where(SNR_DB == 10)[0][0]

        ber_at_10db = ber_curve[idx_10db]

        throughput_factor = bps * (1 - ber_at_10db)

        metrics[mod] = {

            'SNR_Sensitivity_dB':
                float(snr_sensitivity),

            'BER_at_10dB':
                float(ber_at_10db),

            'SpecEff_x_Reliability':
                float(throughput_factor)
        }

    return metrics

# ============================================================
#  DISPLAY BER TABLE
# ============================================================
def display_snr_ber_table(
    ber_bpsk,
    ber_qpsk,
    ber_16qam,
    ber_64qam,
    ber_256qam
):

    snr_points = [
        0, 2, 4, 6, 8,
        10, 12, 14, 16, 18, 20
    ]

    table_data = []

    for snr in snr_points:

        idx = np.where(SNR_DB == snr)[0][0]

        row = [

            f"{snr}",

            f"{ber_bpsk[idx]:.2e}",

            f"{ber_qpsk[idx]:.2e}",

            f"{ber_16qam[idx]:.2e}",

            f"{ber_64qam[idx]:.2e}",

            f"{ber_256qam[idx]:.2e}"
        ]

        table_data.append(row)

    headers = [

        "SNR (dB)",

        "BPSK",

        "QPSK",

        "16-QAM",

        "64-QAM",

        "256-QAM"
    ]

    print("\n" + "="*85)

    print("TABLE 1: SNR vs BER Comparison")

    print("="*85)

    print(
        tabulate(
            table_data,
            headers=headers,
            tablefmt="grid"
        )
    )

# ============================================================
#  DISPLAY METRICS
# ============================================================
def display_performance_metrics(metrics):

    table_data = []

    for mod, metric in metrics.items():

        row = [

            mod,

            f"{metric['SNR_Sensitivity_dB']:.1f} dB",

            f"{metric['BER_at_10dB']:.2e}",

            f"{metric['SpecEff_x_Reliability']:.2f}"
        ]

        table_data.append(row)

    headers = [

        "Modulation",

        "SNR for BER=10^-3",

        "BER at 10 dB",

        "Throughput Factor"
    ]

    print("\n" + "="*85)

    print("TABLE 2: PERFORMANCE METRICS")

    print("="*85)

    print(
        tabulate(
            table_data,
            headers=headers,
            tablefmt="grid"
        )
    )

# ============================================================
#  RUN SIMULATION
# ============================================================
print("=" * 65)
print("Wireless Modulation Project - AWGN Channel Simulation")
print("=" * 65)

print("\nRunning simulations...\n")

ber_bpsk = simulate_bpsk(SNR_DB)
print("✓ BPSK completed")

ber_qpsk = simulate_qpsk(SNR_DB)
print("✓ QPSK completed")

ber_16qam = simulate_qam(SNR_DB, 16)
print("✓ 16-QAM completed")

ber_64qam = simulate_qam(SNR_DB, 64)
print("✓ 64-QAM completed")

ber_256qam = simulate_qam(SNR_DB, 256)
print("✓ 256-QAM completed")

# ============================================================
#  THEORETICAL BER
# ============================================================
ber_bpsk_theory = theoretical_bpsk_ber(SNR_DB_THEORY)

ber_qpsk_theory = theoretical_qpsk_ber(SNR_DB_THEORY)

ber_16qam_theory = theoretical_qam_ber(SNR_DB_THEORY, 16)

ber_64qam_theory = theoretical_qam_ber(SNR_DB_THEORY, 64)

ber_256qam_theory = theoretical_qam_ber(SNR_DB_THEORY, 256)

# ============================================================
#  BER PLOTS
# ============================================================
fig, axes = plt.subplots(3, 2, figsize=(15, 14))

fig.suptitle(
    'BER vs SNR: Modulation Schemes (AWGN Channel)',
    fontsize=15,
    fontweight='bold'
)

plot_cfg = [

    (
        axes[0, 0],
        ber_bpsk,
        ber_bpsk_theory,
        'b',
        'BPSK'
    ),

    (
        axes[0, 1],
        ber_qpsk,
        ber_qpsk_theory,
        'g',
        'QPSK'
    ),

    (
        axes[1, 0],
        ber_16qam,
        ber_16qam_theory,
        'orange',
        '16-QAM'
    ),

    (
        axes[1, 1],
        ber_64qam,
        ber_64qam_theory,
        'red',
        '64-QAM'
    ),

    (
        axes[2, 0],
        ber_256qam,
        ber_256qam_theory,
        'purple',
        '256-QAM'
    )
]

for ax, sim, theory, color, title in plot_cfg:

    ax.semilogy(
        SNR_DB,
        sim,
        color=color,
        marker='o',
        linewidth=2,
        label='Simulated'
    )

    ax.semilogy(
        SNR_DB_THEORY,
        theory,
        color=color,
        linestyle='--',
        linewidth=2,
        label='Theoretical'
    )

    ax.set_xlabel('SNR (dB)')
    ax.set_ylabel('BER')

    ax.set_title(title, fontweight='bold')

    ax.grid(True, which='both', linestyle='--')

    ax.legend()

    ax.set_ylim([1e-6, 1])

axes[2, 1].axis('off')

plt.tight_layout()

plt.savefig(
    'ber_vs_snr_detailed.png',
    dpi=150,
    bbox_inches='tight'
)

plt.show()

print("✓ Saved: ber_vs_snr_detailed.png")

# ============================================================
#  COMBINED BER PLOT
# ============================================================
plt.figure(figsize=(12, 7))

sim_cfg = [

    (ber_bpsk, 'b', 'o', 'BPSK'),

    (ber_qpsk, 'g', 's', 'QPSK'),

    (ber_16qam, 'orange', '^', '16-QAM'),

    (ber_64qam, 'red', 'd', '64-QAM'),

    (ber_256qam, 'purple', 'x', '256-QAM')
]

for sim, color, marker, label in sim_cfg:

    plt.semilogy(
        SNR_DB,
        sim,
        color=color,
        marker=marker,
        linewidth=2,
        label=label
    )

theory_curves = [

    ber_bpsk_theory,

    ber_qpsk_theory,

    ber_16qam_theory,

    ber_64qam_theory,

    ber_256qam_theory
]

theory_colors = [

    'b',

    'g',

    'orange',

    'red',

    'purple'
]

for theory, color in zip(theory_curves, theory_colors):

    plt.semilogy(
        SNR_DB_THEORY,
        theory,
        color=color,
        linestyle='--',
        linewidth=1.5
    )

plt.xlabel(
    'SNR (dB)',
    fontsize=13,
    fontweight='bold'
)

plt.ylabel(
    'Bit Error Rate (BER)',
    fontsize=13,
    fontweight='bold'
)

plt.title(
    'BER vs SNR: All Modulation Schemes (AWGN Channel) ',
    fontsize=14,
    fontweight='bold'
)

plt.grid(True, which='both', linestyle='--')

plt.legend()

plt.ylim([1e-6, 1])

plt.tight_layout()

plt.savefig(
    'ber_vs_snr_comparison.png',
    dpi=150,
    bbox_inches='tight'
)

plt.show()

print("✓ Saved: ber_vs_snr_comparison.png")

# ============================================================
#  CONSTELLATION DIAGRAMS
# ============================================================
plot_constellation_diagrams()

# ============================================================
#  SPECTRAL EFFICIENCY
# ============================================================
plot_spectral_efficiency([
    ber_bpsk,
    ber_qpsk,
    ber_16qam,
    ber_64qam,
    ber_256qam
])

# ============================================================
#  TABLES
# ============================================================
display_snr_ber_table(
    ber_bpsk,
    ber_qpsk,
    ber_16qam,
    ber_64qam,
    ber_256qam
)

# ============================================================
#  PERFORMANCE METRICS
# ============================================================
modulations = [
    'BPSK',
    'QPSK',
    '16-QAM',
    '64-QAM',
    '256-QAM'
]

bits_per_symbol = [1, 2, 4, 6, 8]

ber_curves = [

    ber_bpsk,

    ber_qpsk,

    ber_16qam,

    ber_64qam,

    ber_256qam
]

metrics = calculate_performance_metrics(
    ber_curves,
    modulations,
    bits_per_symbol
)

display_performance_metrics(metrics)

# ============================================================
#  ANALYSIS
# ============================================================
print("\n" + "=" * 65)
print("ADDITIONAL ANALYSIS")
print("=" * 65)

print("\nChannel Conditions:")
print("• Model    : AWGN")
print("• Detector : Nearest Neighbour")
print("• Fading   : None")

print("\nPractical Applications:")
print("• WiFi              : Adaptive BPSK to 256-QAM")
print("• 4G/5G             : QPSK to 256-QAM")
print("• Satellite         : Mostly QPSK")
print("• WiFi 6 / 5G       : 256-QAM for ultra-high data rates")

# ============================================================
#  SAVE RESULTS TO JSON
# ============================================================
results = {

    "modulation_schemes": {},

    "snr_range_db": SNR_DB.tolist()
}

for mod, bps, ber_curve in zip(
    modulations,
    bits_per_symbol,
    ber_curves
):

    results["modulation_schemes"][mod] = {

        "bits_per_symbol": bps,

        "ber_values": ber_curve.tolist()
    }

with open('analysis_results.json', 'w') as f:

    json.dump(results, f, indent=2)

print("\n✓ Saved: analysis_results.json")

# ============================================================
#  COMPLETE
# ============================================================
print("\n" + "=" * 65)
print("SIMULATION COMPLETE!")
print("=" * 65)

print("\nGenerated Files:")
print("1. ber_vs_snr_detailed.png")
print("2. ber_vs_snr_comparison.png")
print("3. constellation_diagrams.png")
print("4. spectral_efficiency_comparison.png")
print("5. analysis_results.json")
print("=" * 65)